apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hurzelpurzel-toolbox
  name:  hurzelpurzel-toolbox
spec:
  containers:
  - image: ghcr.io/hurzelpurzel/workspace/toolbox:main
    imagePullPolicy: Always
    name:  hurzelpurzel-toolbox
