name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TAG: $(date +%s)
      IMAGE_NAME: toolbox
      OWNER: hurzelpurzel

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file toolbox/Containerfile --tag  $IMAGE_NAME:$TAG
    - name: Push Image to registry
      run: docker push ghcr.io/$OWNER/$IMAGE_NAME:$TAG
